import './globals.sass';

import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import { ThemeProvider } from '@/providers/ThemeProvider';
import { PageNavbar } from '@/UI/PageNavbar/PageNavbar';

const notoSans = Noto_Sans({
    variable: '--font-noto-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Tiago Webpage',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning>
            <body className={`${notoSans.variable}`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <PageNavbar>{children}</PageNavbar>
                </ThemeProvider>
            </body>
        </html>
    );
}
