name: Website Update
run-name: ${{ github.actor }} is performing update on website
on:
  push:
    branches:
      - 'main'
jobs:
  update-website-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone tiagoevanp_website and build
      - env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run:
        git clone git@github.com:tiagoevanp/tiagoevanp_website.git
        cd tiagoevanp_website
        pnpm i
        pnpm run build

      - name: Clone tiagoevanp.github.io project
      - env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run:
        git clone git@github.com:tiagoevanp/tiagoevanp.github.io.git
        cd tiagoevanp.github.io
        git config user.name "Tiago Evangelista Pinto"
        git config user.email "tiagoevanp@hotmail.com"

      - name: Copy from tiagoevanp_website/out to tiagoevanp.github.io project
      - run:
        cp -Taf /tiagoevanp_website/out/. /tiago.github.io/
      
      - name: Commit changes and push into main
      - env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run:
        cd tiago.github.io
        git add -A 
        git commit -m "Update new version website"
        git push origin main

