name: update-website
run-name: ${{ github.actor }} is performing update on website
on:
  push:
    branches:
      - 'main'
jobs:
  update-website-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone tiagoevanp_website and build
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10
      - name: Install pnpm packages and build
        run: |
          cd source-repo
          pnpm i
          pnpm run build

      - name: Clone tiagoevanp.github.io project
        uses: actions/checkout@v4
        with:
          repository: 'tiagoevanp/tiagoevanp.github.io'
          path: target-repo

      - name: Configure user.name and user.email
        run: |
          cd target-repo
          git config user.name "Tiago Evangelista Pinto"
          git config user.email "tiagoevanp@hotmail.com"

      - name: Copy from tiagoevanp_website/out to tiagoevanp.github.io project
        run:
          cp -R source-repo/out/* /target-repo/
      
      - name: Commit changes and push into main
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}

